In [1]:
#import NumPy
import numpy as np

In [2]:
# first NumPy array
first_numpy_array = np.array([1,2,3,4])
print (first_numpy_array)

[1 2 3 4]


In [3]:
# array with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

# zeros array --> mentions shape of array within parenthesis
# regular array --> mentions array elements within square brackets

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
#array with empty --> fills the array with random numbers
array_with_empty = np.empty((2,3))
array_with_empty

array([[9.45018104e-308, 3.34871318e-297, 2.47032823e-323],
       [1.45002981e-317, 1.30740363e-316, 0.00000000e+000]])

In [8]:
#array with arange method --> creates arrays with certain data length
np_arange = np.arange(12)   # no. of elements - 12, from 0 to 11
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [9]:
#reshape method to change/create array
np_arange.reshape(3,4)    #3 rows and 4 columns

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
#linspace for linearly (equal) spaced data elements
np_linspace = np.linspace(1,6,5)
print(np_linspace)

# linspace has 3 arguments:
# 1 - the start element of the array
# 2 - the end element of the array
# 3 - interval (total number of equidistant elements)

[1.   2.25 3.5  4.75 6.  ]


In [11]:
#One-dimensional array
OneD_array = np.arange(15)
print(OneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [12]:
#Two-dimensional array (using reshape)
TwoD_array = OneD_array.reshape(3,5)  # 3 rows and 5 columns
print(TwoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [13]:
#Three-dimensional array (using arange and reshape)
ThreeD_array = np.arange(27).reshape(3,3,3)
print(ThreeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
